# Generated by Django 5.0.1 on 2026-01-08 19:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('swap', 'Swap'), ('extra', 'Extra')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shift__date', 'shift__shift_type'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('solver_status', models.CharField(blank=True, max_length=50)),
                ('solver_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('objective_value', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ConstraintViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_violations', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='schedules.schedule')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift (7am-7pm)'), ('night', 'Night Shift (7pm-7am)')], max_length=10)),
                ('start_time', models.TimeField(default='07:00:00')),
                ('end_time', models.TimeField(default='19:00:00')),
                ('min_doctors', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'shift_type'],
                'indexes': [models.Index(fields=['date'], name='schedules_s_date_18e369_idx'), models.Index(fields=['date', 'shift_type'], name='schedules_s_date_50fc0f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('date', 'shift_type'), name='unique_date_shift_type'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedules.shift'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='schedules_s_status_60d460_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['year', 'month'], name='schedules_s_year_054ae5_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('month', 'year'), name='unique_month_year'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['schedule'], name='schedules_c_schedul_0da1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['severity'], name='schedules_c_severit_ceae3b_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['schedule'], name='schedules_s_schedul_de353f_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['doctor'], name='schedules_s_doctor__fda0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift'], name='schedules_s_shift_i_fe4f14_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('schedule', 'shift', 'doctor'), name='unique_schedule_shift_doctor'),
        ),
    ]
