# Generated by Django 5.0.1 on 2026-01-08 19:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_shifts_per_doctor', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_shifts_per_doctor', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_consecutive_shifts', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_rest_hours_between_shifts', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_consecutive_days_off', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('avoid_single_day_off', models.BooleanField(default=True, help_text='Prevent single days off between working shifts')),
                ('default_min_doctors_per_shift', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applies_to', models.CharField(choices=[('all', 'All Shifts'), ('day', 'Day Shifts Only'), ('night', 'Night Shifts Only'), ('weekday', 'Weekdays Only'), ('weekend', 'Weekends Only')], default='all', max_length=20)),
                ('min_with_specialty', models.IntegerField(default=0, help_text='Minimum doctors with this specialty (0 = not required)', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_senior_doctors', models.IntegerField(default=1, help_text='Minimum senior doctors required per shift', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_junior_doctors', models.IntegerField(default=0, help_text='Minimum junior doctors required per shift', validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(default=10, help_text='Higher priority requirements are enforced more strictly (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requirements', to='schedules.scheduleconfiguration')),
                ('required_specialty', models.ForeignKey(blank=True, help_text='Leave blank if no specific specialty required', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.specialty')),
            ],
            options={
                'ordering': ['-priority', 'applies_to'],
            },
        ),
    ]
