# Generated by Django 5.0.1 on 2026-01-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_scheduleconfiguration_shiftrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='min_junior_doctors',
        ),
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='min_senior_doctors',
        ),
    ]
