# Generated by Django 5.0.1 on 2026-01-08 19:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('extra', 'Extra Shift'), ('preference', 'Preference')], max_length=20)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('unfulfilled', 'Unfulfilled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='schedules.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by Target'), ('rejected', 'Rejected by Target'), ('approved', 'Approved by Admin'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_swaps', to=settings.AUTH_USER_MODEL)),
                ('requesting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_swaps', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='schedules.schedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='schedules.shift')),
                ('target_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('study_leave', 'Study Leave'), ('practice_development', 'Practice Development'), ('sick', 'Sick Leave'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['doctor', 'start_date', 'end_date'], name='requests_le_doctor__df400f_idx'), models.Index(fields=['status'], name='requests_le_status_56d20c_idx'), models.Index(fields=['leave_type'], name='requests_le_leave_t_cd0dee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['doctor'], name='requests_sh_doctor__146b79_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['shift'], name='requests_sh_shift_i_3d48d8_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['status'], name='requests_sh_status_a7a4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswap',
            index=models.Index(fields=['status'], name='requests_sh_status_d872f9_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswap',
            index=models.Index(fields=['requesting_doctor'], name='requests_sh_request_7a183b_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswap',
            index=models.Index(fields=['target_doctor'], name='requests_sh_target__797d63_idx'),
        ),
    ]
