# Generated by Django 5.0.1 on 2026-01-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='doctors_doc_experie_5fb6c5_idx',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience_level',
        ),
    ]
